---
- name: add Cloudera CDH5 repository
  copy:
    src: cdh5.repo
    dest: /etc/yum.repos.d/cdh5.repo
    owner: root
    group: root
    mode: 0644

- name: add Cloudera CDH5 key
  rpm_key:
    key: "http://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera"
