---
- name: add Cloudera CDH5 repository
  apt_repository:
    repo: 'deb [arch=amd64] http://archive.cloudera.com/cdh5/debian/wheezy/amd64/cdh wheezy-cdh5 contrib'

- name: add Cloudera CDH5 key
  apt_key:
    url: "http://archive.cloudera.com/cdh5/debian/wheezy/amd64/cdh/archive.key"
