---
# tasks file for avro-sender

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: install flume
  action: "{{ ansible_pkg_mgr }}
    name={{ item }}"
  with_items:
    - flume-ng
    - flume-ng-agent

- name: Configure flume-ng-agent
  template:
    src: flume-conf.j2
    dest: /etc/flume-ng/conf/flume.conf
  notify: restart flume-agent

- name: Set the Flume agent name
  lineinfile:
    dest: /etc/default/flume-ng-agent
    backup: yes
    insertafter: '^# (FLUME_AGENT_NAME=).*'
    line: 'FLUME_AGENT_NAME={{ flume_agent.name }}'
  notify: restart flume-agent
