---
- name: add Cloudera CDH5 repository
  apt_repository:
    repo: 'deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib'

- name: add Cloudera CDH5 key
  apt_key:
    url: "http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh/archive.key"

- name: add java 8 repository
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'

- name: add java 8 key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: EEA14886

- name: install logtail
  apt:
    name: logtail
    update_cache: yes

- name: Auto accept oracle java license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install java 8
  apt:
    name: oracle-java8-installer

- name: get maven 3.2
  get_url:
    url: http://ppa.launchpad.net/natecarlson/maven3/ubuntu/pool/main/m/maven3/maven3_3.2.1-0~ppa1_all.deb
    dest: /tmp/

- name: install maven 3.2
  apt:
    deb: /tmp/maven3_3.2.1-0~ppa1_all.deb

- name: link maven binary
  file:
    src: /usr/bin/mvn3
    dest: /usr/bin/mvn
    state: link
